-- Initial data model of the MVP (phase S2).
--
-- Conventions (ADR 0029):
-- - ids are UUIDv7, generated by the server; timestamps are timestamptz (UTC);
-- - every row owned by a user carries user_id, and references between owned
--   rows go through composite foreign keys (id, user_id), so the database itself
--   refuses to link one user's data to another's;
-- - secrets are stored encrypted (bytea columns ending in _encrypted), with the
--   owner's data key, itself wrapped by the server master key (user_keys);
-- - deleted_at marks soft-deleted rows where a trash applies.

-- +goose Up

CREATE TABLE users (
    id            uuid PRIMARY KEY,
    email         text        NOT NULL,
    display_name  text        NOT NULL DEFAULT '',
    role          text        NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    status        text        NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    password_hash text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX users_email_key ON users (lower(email));

-- One random root key per user, wrapped by a server master key.
CREATE TABLE user_keys (
    user_id       uuid PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    master_key_id text        NOT NULL,
    wrapped_key   bytea       NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    rotated_at    timestamptz
);
CREATE INDEX user_keys_master_key_id_idx ON user_keys (master_key_id);

CREATE TABLE sessions (
    id                 uuid PRIMARY KEY,
    user_id            uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    family_id          uuid        NOT NULL,
    refresh_token_hash bytea       NOT NULL UNIQUE,
    device_name        text        NOT NULL DEFAULT '',
    created_at         timestamptz NOT NULL DEFAULT now(),
    last_used_at       timestamptz NOT NULL DEFAULT now(),
    expires_at         timestamptz NOT NULL,
    revoked_at         timestamptz
);
CREATE INDEX sessions_user_id_idx ON sessions (user_id);
CREATE INDEX sessions_family_id_idx ON sessions (family_id);

-- Second factors and passkeys.
CREATE TABLE credentials (
    id               uuid PRIMARY KEY,
    user_id          uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    kind             text        NOT NULL CHECK (kind IN ('totp', 'webauthn', 'recovery_code')),
    name             text        NOT NULL DEFAULT '',
    secret_encrypted bytea,
    public_key       bytea,
    sign_count       bigint      NOT NULL DEFAULT 0,
    created_at       timestamptz NOT NULL DEFAULT now(),
    last_used_at     timestamptz
);
CREATE INDEX credentials_user_id_idx ON credentials (user_id);

-- Capabilities granted by the admin: globally (user_id NULL) or per user.
CREATE TABLE policies (
    id         uuid PRIMARY KEY,
    user_id    uuid REFERENCES users (id) ON DELETE CASCADE,
    capability text        NOT NULL,
    value      jsonb       NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX policies_scope_key ON policies (coalesce(user_id, '00000000-0000-0000-0000-000000000000'), capability);

-- Provider catalogue: built-in entries and custom ones.
CREATE TABLE providers (
    id          uuid PRIMARY KEY,
    slug        text        NOT NULL UNIQUE,
    name        text        NOT NULL,
    kind        text        NOT NULL CHECK (kind IN ('builtin', 'custom')),
    settings    jsonb       NOT NULL,
    created_by  uuid REFERENCES users (id) ON DELETE SET NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    disabled_at timestamptz
);

CREATE TABLE accounts (
    id                    uuid PRIMARY KEY,
    user_id               uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    provider_id           uuid        NOT NULL REFERENCES providers (id),
    email                 text        NOT NULL,
    display_name          text        NOT NULL DEFAULT '',
    auth_method           text        NOT NULL CHECK (auth_method IN ('password', 'oauth2')),
    credentials_encrypted bytea,
    status                text        NOT NULL DEFAULT 'active'
                          CHECK (status IN ('active', 'reconnect', 'suspended', 'disabled')),
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, user_id),
    UNIQUE (user_id, provider_id, email)
);

CREATE TABLE identities (
    id           uuid PRIMARY KEY,
    user_id      uuid        NOT NULL,
    account_id   uuid        NOT NULL,
    email        text        NOT NULL,
    display_name text        NOT NULL DEFAULT '',
    signature    text        NOT NULL DEFAULT '',
    is_default   boolean     NOT NULL DEFAULT false,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, user_id),
    UNIQUE (account_id, email),
    FOREIGN KEY (account_id, user_id) REFERENCES accounts (id, user_id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX identities_one_default_per_account ON identities (account_id) WHERE is_default;

-- Which actions MagpieMail replays at the provider, per account.
CREATE TABLE sync_policies (
    account_id   uuid PRIMARY KEY,
    user_id      uuid        NOT NULL,
    sync_read    boolean     NOT NULL DEFAULT true,
    sync_flags   boolean     NOT NULL DEFAULT true,
    sync_moves   boolean     NOT NULL DEFAULT false,
    sync_deletes boolean     NOT NULL DEFAULT false,
    sync_tags    boolean     NOT NULL DEFAULT false,
    keep_deleted boolean     NOT NULL DEFAULT true,
    history_days integer CHECK (history_days > 0),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (account_id, user_id) REFERENCES accounts (id, user_id) ON DELETE CASCADE
);

-- Provider-side folders (IMAP mailboxes, Gmail labels).
CREATE TABLE mailboxes (
    id              uuid PRIMARY KEY,
    user_id         uuid        NOT NULL,
    account_id      uuid        NOT NULL,
    name            text        NOT NULL,
    delimiter       text        NOT NULL DEFAULT '/',
    role            text CHECK (role IN ('inbox', 'sent', 'drafts', 'trash', 'junk', 'archive', 'all')),
    uid_validity    bigint,
    uid_next        bigint,
    highest_modseq  bigint,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, user_id),
    UNIQUE (account_id, name),
    FOREIGN KEY (account_id, user_id) REFERENCES accounts (id, user_id) ON DELETE CASCADE
);

-- Content-addressed files. fingerprint is the owner's keyed HMAC-SHA256 of the
-- content (ADR 0030): equal content of one user is stored once.
CREATE TABLE blobs (
    id          uuid PRIMARY KEY,
    user_id     uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    fingerprint bytea       NOT NULL,
    size        bigint      NOT NULL CHECK (size >= 0),
    encrypted   boolean     NOT NULL,
    ref_count   integer     NOT NULL DEFAULT 0 CHECK (ref_count >= 0),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, user_id),
    UNIQUE (user_id, fingerprint)
);
CREATE INDEX blobs_unreferenced_idx ON blobs (updated_at) WHERE ref_count = 0;

CREATE TABLE threads (
    id                 uuid PRIMARY KEY,
    user_id            uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    provider_thread_id text,
    subject            text        NOT NULL DEFAULT '',
    last_message_at    timestamptz,
    created_at         timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, user_id)
);
CREATE INDEX threads_user_last_message_idx ON threads (user_id, last_message_at DESC);

CREATE TABLE messages (
    id                uuid PRIMARY KEY,
    user_id           uuid        NOT NULL,
    account_id        uuid        NOT NULL,
    thread_id         uuid,
    raw_blob_id       uuid,
    message_id_header text,
    in_reply_to       text,
    "references"      text[]      NOT NULL DEFAULT '{}',
    subject           text        NOT NULL DEFAULT '',
    from_address      text        NOT NULL DEFAULT '',
    from_name         text        NOT NULL DEFAULT '',
    to_addresses      jsonb       NOT NULL DEFAULT '[]',
    cc_addresses      jsonb       NOT NULL DEFAULT '[]',
    sent_at           timestamptz,
    received_at       timestamptz NOT NULL,
    size              bigint      NOT NULL DEFAULT 0,
    snippet           text        NOT NULL DEFAULT '',
    has_attachments   boolean     NOT NULL DEFAULT false,
    seen              boolean     NOT NULL DEFAULT false,
    flagged           boolean     NOT NULL DEFAULT false,
    answered          boolean     NOT NULL DEFAULT false,
    auth_results      jsonb,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    deleted_at        timestamptz,
    UNIQUE (id, user_id),
    FOREIGN KEY (account_id, user_id) REFERENCES accounts (id, user_id) ON DELETE CASCADE,
    FOREIGN KEY (thread_id, user_id) REFERENCES threads (id, user_id) ON DELETE SET NULL (thread_id),
    FOREIGN KEY (raw_blob_id, user_id) REFERENCES blobs (id, user_id) ON DELETE RESTRICT
);
-- List views: per account and over all accounts, newest first, trash excluded.
CREATE INDEX messages_account_received_idx ON messages (account_id, received_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX messages_user_received_idx ON messages (user_id, received_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX messages_thread_idx ON messages (thread_id);
CREATE INDEX messages_message_id_idx ON messages (user_id, message_id_header);
CREATE INDEX messages_deleted_idx ON messages (user_id, deleted_at) WHERE deleted_at IS NOT NULL;

-- Where a message sits at the provider: one row per mailbox (Gmail labels).
CREATE TABLE message_locations (
    message_id uuid   NOT NULL,
    mailbox_id uuid   NOT NULL,
    user_id    uuid   NOT NULL,
    uid        bigint NOT NULL,
    PRIMARY KEY (message_id, mailbox_id),
    UNIQUE (mailbox_id, uid),
    FOREIGN KEY (message_id, user_id) REFERENCES messages (id, user_id) ON DELETE CASCADE,
    FOREIGN KEY (mailbox_id, user_id) REFERENCES mailboxes (id, user_id) ON DELETE CASCADE
);

CREATE TABLE tags (
    id         uuid PRIMARY KEY,
    user_id    uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name       text        NOT NULL,
    color      text        NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, user_id)
);
CREATE UNIQUE INDEX tags_user_name_key ON tags (user_id, lower(name));

CREATE TABLE message_tags (
    message_id uuid NOT NULL,
    tag_id     uuid NOT NULL,
    user_id    uuid NOT NULL,
    PRIMARY KEY (message_id, tag_id),
    FOREIGN KEY (message_id, user_id) REFERENCES messages (id, user_id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id, user_id) REFERENCES tags (id, user_id) ON DELETE CASCADE
);
CREATE INDEX message_tags_tag_idx ON message_tags (tag_id);

-- MagpieMail's own folders, accepting messages from any account of the user.
CREATE TABLE global_folders (
    id         uuid PRIMARY KEY,
    user_id    uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    parent_id  uuid,
    name       text        NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, user_id),
    FOREIGN KEY (parent_id, user_id) REFERENCES global_folders (id, user_id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX global_folders_sibling_name_key
    ON global_folders (user_id, coalesce(parent_id, '00000000-0000-0000-0000-000000000000'), lower(name));

CREATE TABLE global_folder_messages (
    folder_id  uuid        NOT NULL,
    message_id uuid        NOT NULL,
    user_id    uuid        NOT NULL,
    added_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (folder_id, message_id),
    FOREIGN KEY (folder_id, user_id) REFERENCES global_folders (id, user_id) ON DELETE CASCADE,
    FOREIGN KEY (message_id, user_id) REFERENCES messages (id, user_id) ON DELETE CASCADE
);
CREATE INDEX global_folder_messages_message_idx ON global_folder_messages (message_id);

CREATE TABLE attachments (
    id           uuid PRIMARY KEY,
    user_id      uuid        NOT NULL,
    message_id   uuid        NOT NULL,
    blob_id      uuid        NOT NULL,
    filename     text        NOT NULL DEFAULT '',
    content_type text        NOT NULL DEFAULT 'application/octet-stream',
    size         bigint      NOT NULL DEFAULT 0,
    content_id   text,
    inline       boolean     NOT NULL DEFAULT false,
    created_at   timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (message_id, user_id) REFERENCES messages (id, user_id) ON DELETE CASCADE,
    FOREIGN KEY (blob_id, user_id) REFERENCES blobs (id, user_id) ON DELETE RESTRICT
);
CREATE INDEX attachments_message_idx ON attachments (message_id);

CREATE TABLE drafts (
    id                     uuid PRIMARY KEY,
    user_id                uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    identity_id            uuid,
    in_reply_to_message_id uuid,
    subject                text        NOT NULL DEFAULT '',
    body_text              text        NOT NULL DEFAULT '',
    body_html              text        NOT NULL DEFAULT '',
    to_addresses           jsonb       NOT NULL DEFAULT '[]',
    cc_addresses           jsonb       NOT NULL DEFAULT '[]',
    bcc_addresses          jsonb       NOT NULL DEFAULT '[]',
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz NOT NULL DEFAULT now(),
    deleted_at             timestamptz,
    UNIQUE (id, user_id),
    FOREIGN KEY (identity_id, user_id) REFERENCES identities (id, user_id) ON DELETE SET NULL (identity_id),
    FOREIGN KEY (in_reply_to_message_id, user_id) REFERENCES messages (id, user_id)
        ON DELETE SET NULL (in_reply_to_message_id)
);
CREATE INDEX drafts_user_updated_idx ON drafts (user_id, updated_at DESC) WHERE deleted_at IS NULL;

-- Messages waiting to be sent: undo delay, scheduled sending, retries.
CREATE TABLE outbox (
    id              uuid PRIMARY KEY,
    user_id         uuid        NOT NULL,
    account_id      uuid        NOT NULL,
    identity_id     uuid        NOT NULL,
    blob_id         uuid        NOT NULL,
    idempotency_key text        NOT NULL,
    status          text        NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'sending', 'sent', 'failed', 'cancelled')),
    send_after      timestamptz NOT NULL,
    attempts        integer     NOT NULL DEFAULT 0,
    last_error      text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    sent_at         timestamptz,
    UNIQUE (user_id, idempotency_key),
    FOREIGN KEY (account_id, user_id) REFERENCES accounts (id, user_id) ON DELETE CASCADE,
    FOREIGN KEY (identity_id, user_id) REFERENCES identities (id, user_id) ON DELETE CASCADE,
    FOREIGN KEY (blob_id, user_id) REFERENCES blobs (id, user_id) ON DELETE RESTRICT
);
CREATE INDEX outbox_due_idx ON outbox (send_after) WHERE status = 'pending';

-- Security-relevant events: sign-ins, failures, security changes, admin
-- actions, outbound calls. Never message content, tokens or passwords.
CREATE TABLE audit_log (
    id            uuid PRIMARY KEY,
    occurred_at   timestamptz NOT NULL DEFAULT now(),
    actor_user_id uuid REFERENCES users (id) ON DELETE SET NULL,
    action        text        NOT NULL,
    target_type   text        NOT NULL DEFAULT '',
    target_id     text        NOT NULL DEFAULT '',
    client_ip     inet,
    details       jsonb       NOT NULL DEFAULT '{}'
);
CREATE INDEX audit_log_occurred_idx ON audit_log (occurred_at DESC);
CREATE INDEX audit_log_actor_idx ON audit_log (actor_user_id, occurred_at DESC);

-- +goose Down

DROP TABLE audit_log;
DROP TABLE outbox;
DROP TABLE drafts;
DROP TABLE attachments;
DROP TABLE global_folder_messages;
DROP TABLE global_folders;
DROP TABLE message_tags;
DROP TABLE tags;
DROP TABLE message_locations;
DROP TABLE messages;
DROP TABLE threads;
DROP TABLE blobs;
DROP TABLE mailboxes;
DROP TABLE sync_policies;
DROP TABLE identities;
DROP TABLE accounts;
DROP TABLE providers;
DROP TABLE policies;
DROP TABLE credentials;
DROP TABLE sessions;
DROP TABLE user_keys;
DROP TABLE users;
