// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for HealthStatusStatus.
const (
	Ok HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Features Optional features and whether they are enabled on this instance. New
// features are added as new members; clients must ignore unknown members.
type Features struct {
	// Ai AI features (summaries, classification).
	Ai bool `json:"ai"`

	// Documents Document Mode (text extraction and OCR of attachments).
	Documents bool `json:"documents"`

	// WebPush Notifications through the browser's push service.
	WebPush bool `json:"webPush"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status HealthStatusStatus `json:"status"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// Info defines model for Info.
type Info struct {
	// ApiVersion Version of this API contract (semantic versioning).
	ApiVersion string `json:"apiVersion"`

	// Features Optional features and whether they are enabled on this instance. New
	// features are added as new members; clients must ignore unknown members.
	Features Features `json:"features"`
}

// Problem RFC 9457 problem details. Clients identify a problem by `type`. More
// members may be added: clients must ignore members they do not know.
type Problem struct {
	// Detail Human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Instance Identifies this occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// RequestId ID of the request, as in the `X-Request-ID` response header.
	RequestId *string `json:"requestId,omitempty"`

	// Status HTTP status code.
	Status int `json:"status"`

	// Title Short, human-readable summary of the problem type.
	Title string `json:"title"`

	// Type Identifies the problem type. `about:blank` for generic HTTP errors.
	Type string `json:"type"`
}

// HealthOK defines model for HealthOK.
type HealthOK = HealthStatus

// InternalError RFC 9457 problem details. Clients identify a problem by `type`. More
// members may be added: clients must ignore members they do not know.
type InternalError = Problem

// ServiceUnavailable RFC 9457 problem details. Clients identify a problem by `type`. More
// members may be added: clients must ignore members they do not know.
type ServiceUnavailable = Problem

// TooManyRequests RFC 9457 problem details. Clients identify a problem by `type`. More
// members may be added: clients must ignore members they do not know.
type TooManyRequests = Problem

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetInfo Describe the instance
	// (GET /api/v1/info)
	GetInfo(w http.ResponseWriter, r *http.Request)
	// GetLiveness Liveness probe
	// (GET /healthz)
	GetLiveness(w http.ResponseWriter, r *http.Request)
	// GetReadiness Readiness probe
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetInfo Describe the instance
// (GET /api/v1/info)
func (_ Unimplemented) GetInfo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetLiveness Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetLiveness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReadiness Readiness probe
// (GET /readyz)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetInfo operation middleware
func (siw *ServerInterfaceWrapper) GetInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/info", wrapper.GetInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetLiveness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadiness)
	})

	return r
}

type HealthOKJSONResponse HealthStatus

type InternalErrorApplicationProblemPlusJSONResponse Problem

type ServiceUnavailableApplicationProblemPlusJSONResponse Problem

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type GetInfoRequestObject struct {
}

type GetInfoResponseObject interface {
	VisitGetInfoResponse(w http.ResponseWriter) error
}

type GetInfo200JSONResponse Info

func (response GetInfo200JSONResponse) VisitGetInfoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetInfo429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response GetInfo429ApplicationProblemPlusJSONResponse) VisitGetInfoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetInfo500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetInfo500ApplicationProblemPlusJSONResponse) VisitGetInfoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetLivenessRequestObject struct {
}

type GetLivenessResponseObject interface {
	VisitGetLivenessResponse(w http.ResponseWriter) error
}

type GetLiveness200JSONResponse struct{ HealthOKJSONResponse }

func (response GetLiveness200JSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetLiveness500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetLiveness500ApplicationProblemPlusJSONResponse) VisitGetLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse struct{ HealthOKJSONResponse }

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness500ApplicationProblemPlusJSONResponse struct {
	InternalErrorApplicationProblemPlusJSONResponse
}

func (response GetReadiness500ApplicationProblemPlusJSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness503ApplicationProblemPlusJSONResponse struct {
	ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response GetReadiness503ApplicationProblemPlusJSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetInfo Describe the instance
	// (GET /api/v1/info)
	GetInfo(ctx context.Context, request GetInfoRequestObject) (GetInfoResponseObject, error)
	// GetLiveness Liveness probe
	// (GET /healthz)
	GetLiveness(ctx context.Context, request GetLivenessRequestObject) (GetLivenessResponseObject, error)
	// GetReadiness Readiness probe
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetInfo operation middleware
func (sh *strictHandler) GetInfo(w http.ResponseWriter, r *http.Request) {
	var request GetInfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInfo(ctx, request.(GetInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInfoResponseObject); ok {
		if err := validResponse.VisitGetInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLiveness operation middleware
func (sh *strictHandler) GetLiveness(w http.ResponseWriter, r *http.Request) {
	var request GetLivenessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLiveness(ctx, request.(GetLivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLiveness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLivenessResponseObject); ok {
		if err := validResponse.VisitGetLivenessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFl7cxu3Ef8qO5fMRJ4cKerlRPT0D41Ux2xiS7XktjOmGoK4JQ/RHXDB4kixHn73zgL34kOKPW6mf4l3",
	"B+z+sI/f7kKfImnywmjUjqLhpyhFkaD1P9+js6uLmUPLTwmStKpwyuhoGN2iNDohcAaWQjmY4sxYBMtb",
	"lJ73ozjCR5EXGUbD4zgimWIuWEyutMrLPBoexZFbFRgNI6UdztFG6/U6jixSYTShR/AGRebS65/5tzTa",
	"oXb8UxRFpqRgKIe/EeP51Gr7FJETrqRoGJmHaN3V/a3FWTSMvjlsj3wYvtJhUHUbtnokmwe+SxEKa6YI",
	"VEqJmGDSZ+kj7dBqkf3VWmOfwcl7M8y/34M3QSdUFg2jCw2lxscCpcMEkCWCkbK0lpWxbX4vkdwoiYbR",
	"4Oj8eHYiTntn05ey90PyI/bOZ4NB7+jo+Pjk5PT07OzlyyhubHE2GMSRU441NpjhFu0CLQTsjT/E1JRu",
	"OM2E/gL73YTz7TPds8eCK396AmERlAaXIlCAlZk5gdHZyhuasSqJH7RYCJWJaYZfaW32aCKcmApCUATa",
	"OLAoZMqyv9rcJ625K+TQhf7nGRsSLFAnqOWKT1W2Sr0Z74x5K/TqfTgbfaUN3wuHkKlcOcDHkBWvAglA",
	"JhzarzTj6fF5a8Y7Y4ChQ4P9TzPinmPxSba5sdeQ4z491erDDo2uva4KAO97jcKVNpDdJoRr/0NkMKuW",
	"gNAJLFN0KVrOkpXPGNTs2QQMZ44iUJqc0BL78A6XY91utggiSTABQaBxCTnmU7T0CmSmGC7kJTlQc20s",
	"QqkftFnqelF/rKM4Kqwp0DoV0Aq1i/li1KI9oDLPhVVIMchMEKlZFVgv+q3jpsZkKDQ7LTGyzOsqtCn3",
	"qvoEb02CcODwkf3irJC8wBvm+vI9mBkI54RMvZgn1CxxelNSuqvknXENRAKXWlPOU09HU2uWhPY7gqKk",
	"1LOTkrhP/DpEu7KYRMOPbKPuuVrl981WM/0NpWNgGwVo+GnL3NS8l0aTC8WtkULOKj3f0V9t2qdtpGdm",
	"V4so1D/QkjJ61z7VB7ayj7SLmxEwc7AX4IAwF9opCYuwTOn5i40mIBr0j/oDDiPhHFqW+O/xOPl+PO53",
	"/ny7e6Y4mnWS5LmEbpJpxw/tsTrS9pml5oSd079/fQnnp2c/QMWKECiQ+nBZ5Y9KUDs1W4Fo1kxXMGEV",
	"kz68NRbHusonyMUKplVCDvdmYL3SJ3pifHHinNyXijUbb2N+U+ZC9yyKhDkC8LHIhPbxDVSg5GgHZ4I3",
	"q3qsJW567Z0Bi2RKK1mAIkcgXNgiksQiUX+fy2oa2gU1CmZSSNuKQ2RhbT2WOzM2FxzspVU9izP0C/cp",
	"7BSZHY1XteRqUcwcWLUak3/1qnLSG11NoO4+IZD3VgR/XvHawdbm7pZ/7u5uIHwEaZJNy58OTuMoF4+h",
	"WT47P4/b1vl0MGjUNM1zUyh3WvXUWBdDuhkNgZ5XW0YHlrodAQ5em1In+44WXjzr4y3ZMOkU6wnMjIU5",
	"arRKgreHbw9pE0JnxxcExRYJ+K+1keKnuZEdhrK0yq1umVhCjk1RWLQXpUvbp9c1EFOI30sWutP3hi8g",
	"pEQicOYBdezPzHm4wDr1Y7i9+jlU+NSYB+rDDVry5f/iZjTWfiNBSRj6Y5E3Eer5wDOgr0QeWGuL1LmC",
	"/SSNeVBYw9+dbAjJk3tYVwfFEqcVQjiYvHGuuNbZ6hXcsnnwFdyKHG+Vw7/cOqukm7wIYBQLDYKiONLC",
	"A/v11zeGXC8X80Lhr5W6Fqco1M+4Cq2YqkrTLsqinGZK+spTIXzr5b0VKquGhoaPg0njYE9v2SCNxppH",
	"Ck+m3WGjLfiKmrrWH+ux/uYbuDR6wSFtNPGbHlTlhBuvAm3VM2Ts0VInaGFyKAp1uDia9OGfyqVKt29i",
	"kKnQ89CTjTUwjyofDMZbV8DUonhQel4tZBWaagHHkz4D8CObFwFPlSY4mDzVzk9e9OGnkHWMoJN4PsZ8",
	"0RpCN1FfBbb02TMBFRK7S2DclAVkC7SrlkilsFbxYfU211YBDH8vjUNQjptbDRYLYx2fXjC0CvWQv3PN",
	"ycgEJA3hT6paySGxXZwZzy++aPGxZGnJWCjEXIUyOIRCUDjKROOju/QLJixJ8DLkQuFS76WJrD4Wwooc",
	"HVqunXN0fjvvBqPx1aYgRTDRZZZNQn+OkAlyXrKH1vBk5ckPH0ZXix8gEBj14Uq4qnX/cHcZc8liX5+c",
	"nJzDIYxur+HHl4MjCHzoBf7t9vpd0zrwPilyzC4FBX314OQ/2WbGwQQKtHWmV2Xdpwy/LgktR2W1lG1R",
	"2Z5PTzA5PT6fwFK5FARMOnPRpKWoHnzQWRDaJgyQWBEYl6JdKsKYXVwRNoEoXcrGkZWjBARqY/WeDeFg",
	"H4W+AGOrrN4gtIOWyiqWypRETb54qcYN0TB6O7prWYsfuB6EWulH+WzWSw05TGIorFoIuerNlCUHOZOQ",
	"mM8tzqvjBUKK2gm2w1YXN6MojhZ1s111x+s44mQXhYqG0UnbMKe+BlUMclgT5BzdnkYVXWl1CGomykqF",
	"dye/awa0pybHGMiMtUuFA1HHhBQaZIryAbjtFk5NVabcqr71IzXnhh+U7sPIQWLQ36aMtcUFiqxDs98R",
	"4CMPDNNSZUnwRBMQ/obgJ3R+Ntm6CTweDL7sErA7yjSzR3eS4AF2JjLCjdGzetNMif55/dl3Ch76nguF",
	"UWVcYN9xuiqj/XXM6fH5UzKb8x9u39ms4+hsMPjjfZt3k93OJhp+vO/G9ZVHOw3tRdO8x5ETc/KT5Ioc",
	"5tE9y+CLjcyl/3kyBC80LdESHA8GTKCZYTJvWkHfCfloIF9AfMj44OKg6dxexWPtyZ4DUYOxMkVyVjhj",
	"QSOXbIvkhHXULeNTlKJuk+rLvbFWBIlZ6j5wM9slvici8Be1QI1ET0Th81ZvLq3/926qcYWb6I5/gksq",
	"/3CPv/o89/iS2zEfJ3pimPNnZQZLYx+GG6YEETaP9TK0NcdA4T8Bn23b9ygS9X8zLu86+eNdey6bn/NL",
	"c6ZnHLO5fXOi+Hi/jj9tNOkf79eswXuF/Prddnin+QXlCLMZl5zS8vXsYbS+b7DsTGktFYVWbyP5+20V",
	"rJJ/HW9LaMKRi4vdtAH5MaebtdSH69KRSrDTHrdaKkut79f/HQA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
